name: Docker Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    if: ${{github.ref == 'refs/heads/main'}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Node v18
        uses: actions/setup-node@v1
        with:
          node-version: v18.19.0

      - uses: actions/cache@v3
        with:
          path: |
            .next
            .yarn/cache
            ./node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn export

      - name: Build docker and publish
        run: |
          docker build -t crustio/cloud3-home:latest .
          docker login -u ${{ secrets.DOCKER_HUB_USER_NAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker push crustio/cloud3-home:latest
      - name: Update docker compose
        uses: fifsky/ssh-action@master
        with:
          command: ${{ secrets.RUN_CMD }}
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}